configuration:

  status: warn
  packages: com.datastax.logging.appender

  ThresholdFilter:
    level: info

  appenders:
    Console:
      name: Console
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#   File:
#     name: File
#     # Set a Java property like this to set a log fine name:
#     # -Dapp.log="/home/foo/var/abc.log"
#     fileName: "${app.log}"
#     PatternLayout:
#       Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    CassandraAppender:
       name: CassandraAppender
       ThresholdFilter:
         level: info

  loggers:
    root:
      level: info
      AppenderRef:
        - ref: Console
#       - ref: File
        - ref: CassandraAppender
